version: '3.8'

services:
  tarantool:
    build: ./tarantool
    ports:
      - "3301:3301"
    volumes:
      - tarantool_data:/var/lib/tarantool
    restart: unless-stopped

  poll-bot:
    build: ./src
    depends_on:
      - tarantool
    restart: unless-stopped
  environment:
      - BOT_TOKEN
      - BOT_PORT
      - MM_URL
      - DB_HOST
      - DB_PORT

volumes:
  tarantool_data:
